### ISSUE TITLE
Generating Denormalized TPCH Dataset date time dependency error

### ISSUE THREAD

**Issue by snkavuri** [SparklineData/spark-datetime#15]
**This is the command I used learning from here:** https://github.com/SparklineData/spark-druid-olap/wiki/Generating-Denormalized-TPCH-Dataset

bin/spark-submit \ --packages com.databricks:spark-csv_2.10:1.1.0,com.sparklinedata:spark-datetime:0.0.2,SparklineData:spark-druid-olap:0.1.0 \ --class org.sparklinedata.tpch.TpchGenMain \ /home/temp/tpch-spark-druid/tpchData/target/scala-2.10/tpchdata_2.10-0.0.1.jar \ --baseDir /home/temp/tpch-spark-data --scale 1

**I got an error:**

==== spark-packages: tried

  http://dl.bintray.com/spark-packages/maven/com/github/SparklineData/spark-datetime/bf5693a575a1dea5b663e4e8b30a0ba94c21d62d/spark-datetime-bf5693a575a1dea5b663e4e8b30a0ba94c21d62d.pom

  -- artifact com.github.SparklineData#spark-datetime;bf5693a575a1dea5b663e4e8b30a0ba94c21d62d!spark-datetime.jar:

  http://dl.bintray.com/spark-packages/maven/com/github/SparklineData/spark-datetime/bf5693a575a1dea5b663e4e8b30a0ba94c21d62d/spark-datetime-bf5693a575a1dea5b663e4e8b30a0ba94c21d62d.jar

    ::::::::::::::::::::::::::::::::::::::::::::::

    ::          UNRESOLVED DEPENDENCIES         ::

    ::::::::::::::::::::::::::::::::::::::::::::::

    :: com.sparklinedata#spark-datetime;0.0.3: not found

    :: com.github.SparklineData#spark-datetime;bf5693a575a1dea5b663e4e8b30a0ba94c21d62d: not found

:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: com.sparklinedata#spark-datetime;0.0.3: not found, unresolved dependency: com.github.SparklineData#spark-datetime;bf5693a575a1dea5b663e4e8b30a0ba94c21d62d: not found] at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1303) at org.apache.spark.deploy.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:53) at org.apache.spark.deploy.SparkSubmit$.doPrepareSubmitEnvironment(SparkSubmit.scala:364) at org.apache.spark.deploy.SparkSubmit$.prepareSubmitEnvironment(SparkSubmit.scala:250) at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:171) at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137) at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

This resembles the same error in https://github.com/SparklineData/spark-druid-olap/issues/45 but that fix didnot work

**Comment by snkavuri** [comment]
Resolved this issue by updating build.sbt with correct date time version in the target folder
