### ISSUE TITLE
datetime fails on collect

### ISSUE THREAD

**Issue by sdesikan6** [SparklineData/spark-datetime#2]
import com.github.nscala_time.time.Imports._
import org.apache.spark.sql.catalyst.dsl.expressions._
import org.sparklinedata.spark.dateTime.dsl.expressions._
//org.sparklinedata.spark.dateTime.Functions.register(hc)
val dT = dateTime('e_log_time)
val dT1 = dateTime('e_log_time) - 8.months
val dOW = dateTime('e_log_time) dayOfWeekName
val dOM = dateTime('e_log_time) dayOfMonth
val dOY = dateTime('e_log_time) dayOfYear
//val dOWNm = dateTime('e_log_time) dayOfWeekName
//val dOWNm2 = dateTimeWithTZ('e_log_time) dayOfWeekName
//val dTPST = dateTimeWithTZ('e_log_time) 
//val dTFixed = dateTime("2015-05-22T08:52:41.903-07:00")
val sqlStr = date"select e_log_time, $dT, $dT1, $dOW, $dOM, $dOY from eventlog_sessions"
val t = sql(sqlStr)
t.cache
t.show
t.registerTempTable("dateTest")
import com.github.nscala_time.time.Imports._
import org.apache.spark.sql.catalyst.dsl.expressions._
import org.sparklinedata.spark.dateTime.dsl.expressions._
dT: org.sparklinedata.spark.dateTime.dsl.DateExpression = org.sparklinedata.spark.dateTime.dsl.package$DateExpression@f435268
dT1: org.sparklinedata.spark.dateTime.dsl.DateExpression = org.sparklinedata.spark.dateTime.dsl.package$DateExpression@5f986a78
warning: there were 1 feature warning(s); re-run with -feature for details
dOW: org.apache.spark.sql.catalyst.expressions.Expression = 'dayOfWeekName('dateTime('e_log_time))
warning: there were 1 feature warning(s); re-run with -feature for details
dOM: org.apache.spark.sql.catalyst.expressions.Expression = 'dayOfMonth('dateTime('e_log_time))
warning: there were 1 feature warning(s); re-run with -feature for details
dOY: org.apache.spark.sql.catalyst.expressions.Expression = 'dayOfYear('dateTime('e_log_time))
sqlStr: String = select e_log_time, dateTime(`e_log_time`), dateMinus(dateTime(`e_log_time`),period("P8M")), dayOfWeekName(dateTime(`e_log_time`)), dayOfMonth(dateTime(`e_log_time`)), dayOfYear(dateTime(`e_log_time`)) from eventlog_sessions
t: org.apache.spark.sql.DataFrame = [e_log_time: string, _c1: sparkdatetim, _c2: sparkdatetim, _c3: string, _c4: int, _c5: int]
res362: t.type = [e_log_time: string, _c1: sparkdatetim, _c2: sparkdatetim, _c3: string, _c4: int, _c5: int]
org.apache.spark.SparkException: Job aborted due to stage failure: Task 12 in stage 1430.0 failed 4 times, most recent failure: Lost task 12.3 in stage 1430.0 (TID 54364, 172.31.57.134): java.lang.IllegalArgumentException: Invalid format: "2015-05-28T09:30:35Z" is malformed at "Z"
    at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:866)
    at org.sparklinedata.spark.dateTime.Functions$.parseDate(Functions.scala:284)
    at org.sparklinedata.spark.dateTime.Functions$.dateTimeFn(Functions.scala:53)
    at org.sparklinedata.spark.dateTime.Functions$$anonfun$register$2.apply(Functions.scala:190)
    at org.sparklinedata.spark.dateTime.Functions$$anonfun$register$2.apply(Functions.scala:190)
    at org.apache.spark.sql.catalyst.expressions.ScalaUdf$$anonfun$2.apply(ScalaUdf.scala:71)
    at org.apache.spark.sql.catalyst.expressions.ScalaUdf$$anonfun$2.apply(ScalaUdf.scala:70)
    at org.apache.spark.sql.catalyst.expressions.ScalaUdf.eval(ScalaUdf.scala:960)
    at org.apache.spark.sql.catalyst.expressions.Alias.eval(namedExpressions.scala:118)
    at org.apache.spark.sql.catalyst.expressions.InterpretedMutableProjection.apply(Projection.scala:68)
    at org.apache.spark.sql.catalyst.expressions.InterpretedMutableProjection.apply(Projection.scala:52)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
    at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103)
    at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47)
    at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
    at scala.collection.AbstractIterator.to(Iterator.scala:1157)
    at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265)
    at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1157)
    at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:252)
    at scala.collection.AbstractIterator.toArray(Iterator.scala:1157)
    at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:885)
    at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:885)
    at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1765)
    at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1765)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:63)
    at org.apache.spark.scheduler.Task.run(Task.scala:70)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
    at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1266)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1257)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1256)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
    at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1256)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:730)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:730)
    at scala.Option.foreach(Option.scala:236)
    at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:730)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1450)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1411)
    at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)

**Comment by hbutani** [comment]
I cannot reproduce. Can you test with the latest jar. Also can you provide the version of joda being used. The stacktrace line numbers for Functions.parseDate and DateTimeFormatter.parseDateTime don't match the current version.
