### ISSUE TITLE
How do you specify the date format? 

### ISSUE THREAD

**Issue by KristinaPlazonic** [SparklineData/spark-datetime#5]
My date string is in the format "2015-04-25 00:00:00"  in the column "mydate" in table "phonedf".  

I.e. my date format is "yyyy-MM-dd HH:mm:ss"  - I can parse this string with the following code:
import com.github.nscala_time.time.Imports._  // in order to have DateTimeFormat
DateTimeFormat.forPattern("yyyy-MM-dd HH:mm:ss").parseDateTime("2015-04-25 00:00:00")  

When I run your basic example in spark-shell I get the following error: 
scala> sql(date"select mydate, $dT from phonedf").show()
15/07/19 18:40:24 WARN TaskSetManager: Lost task 0.0 in stage 2.0 (TID 5, 66.6.134.202): java.lang.IllegalArgumentException: Invalid format: "2015-04-25 00:00:00" is malformed at " 00:00:00"
    at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:899)
    at org.joda.time.DateTime.parse(DateTime.java:160)
    at org.joda.time.DateTime.parse(DateTime.java:149)
    at org.sparklinedata.spark.dateTime.Functions$.parseDate(Functions.scala:363)
    at org.sparklinedata.spark.dateTime.Functions$.dateTimeFn(Functions.scala:59)
    at org.sparklinedata.spark.dateTime.Functions$$anonfun$register$2.apply(Functions.scala:243)
    at org.sparklinedata.spark.dateTime.Functions$$anonfun$register$2.apply(Functions.scala:243)
    at org.apache.spark.sql.catalyst.expressions.ScalaUdf$$anonfun$2.apply(ScalaUdf.scala:71)
    at org.apache.spark.sql.catalyst.expressions.ScalaUdf$$anonfun$2.apply(ScalaUdf.scala:70)
    at org.apache.spark.sql.catalyst.expressions.ScalaUdf.eval(ScalaUdf.scala:960)
    at org.apache.spark.sql.catalyst.expressions.Alias.eval(namedExpressions.scala:118)
    at org.apache.spark.sql.catalyst.expressions.InterpretedMutableProjection.apply(Projection.scala:68)
    at org.apache.spark.sql.catalyst.expressions.InterpretedMutableProjection.apply(Projection.scala:52)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
    at scala.collection.Iterator$$anon$10.next(Iterator.scala:312)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)

**Comment by hbutani** [comment]
Fixed in commit: 57ab1bd074c6ea06adaf7c20bba67e0c6c936b18

You can say:

``` scala
val dT = dateTime('mydate, Some("yyyy-MM-dd HH:mm:ss"))
sql(date"select mydate, $dT from phonedf").show()
```

for a complete e.g. see the 'issue5' test in IssuesTest

**Comment by KristinaPlazonic** [comment]
Thanks, it works! And thanks for the package!!!

Btw, you have two typos in your README.md: 
1. in the Linking section, it should not be "artifactId: spark-csv_2.10"
2. in the very end, Building from Source section, it should be "build/sbt package", not "sbt/sbt package" (at least, that's what worked for me)

**Comment by hbutani** [comment]
Thanks for the feedback; have fixed the README
